# Generated by Django 3.1.4 on 2021-01-07 21:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210107_1606'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='billingprofile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
