# Generated by Django 3.1.4 on 2021-01-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210108_0041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='billingprofile',
            managers=[
            ],
        ),
    ]
